version: '3.8'


services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=BeakPeak;User=sa;Password=MillenniumDB@1;
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server2022
    ports:
    - "1433:1433"
    environment:
    - ACCEPT_EULA=y
    - SA_PASSWORD=MillenniumDB@1
    volumes:
      - ./scripts/sqlscripts:/docker-entrupoint-intidb.d
