version: '3.8'

services:
  webapi:
    container_name: webapi
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - db
    develop:
      watch:
        - path: .
          action: rebuild 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=BeakPeek;User=sa;Password=Your_password123;TrustServerCertificate=true;
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server2022
    ports:
    - "1433:1433"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    volumes:
      - ./scripts/sqlscripts:/docker-entrypoint-initdb.d
      - ./res/species/test_docker_list.csv:/tmp/province_gauteng_specieslist.csv
      - ./scripts/bash/custom-entrypoint.sh:/usr/config/custom-entrypoint.sh
    command: ["/bin/bash", "/usr/config/custom-entrypoint.sh"]
