name: 📄 Generate coverage for both 🥅 dotnet and 🦚 Flutter

on:
  push:
    branches:
      - main
      - development
      - '**devops**'
      - '**test**'
    paths:
      - 'beakpeek/**'
      - 'dotnet/BirdApi'
      - '.github/workflows/coverage.yml'

  workflow_call:
  workflow_dispatch:

# Don't forget that "!" is used to check if something is set

concurrency:
  group: coverage-${{ github.ref }}
  cancel-in-progress: true
jobs:
  flutter-coverage:
    name: 🦚 Flutter Coverage
    uses: ./.github/workflows/flutter.yml
    with: 
      upload-coverage: true # this has to be true to not upload coverage
    secrets: inherit

  dotnet-coverage:
    name: 🥅 Dotnet Coverage
    uses: ./.github/workflows/dotnet.yml
    with:
      upload-coverage: true
    secrets: inherit

  upload-coverage:
    runs-on: ubuntu-latest
    name: 📔 Upload to codecov
    needs: [flutter-coverage, dotnet-coverage]
    steps:
    - uses: actions/checkout@v4

    - name: Get Flutter Code Coverage
      if: ${{ steps.has-coverage.outputs.exists == false }}
      uses: actions/download-artifact@v4
      id: get-coverage
      with:
        name: flutter-code-coverage-${{hashFiles('beakpeek/pubspec.lock')}}

    - name: Get Dotnet Code Coverage
      if: ${{ steps.has-coverage.outputs.exists == false }}
      uses: actions/download-artifact@v4
      id: get-coverage
      with:
        name: dotnet-code-coverage-${{hashFiles('dotnet/BirdApi/BeakPeekApi/packages.lock.json', 'dotnet/BirdApi/BeakPeekApi.Tests/packages.lock.json')}}


    - name: unzip dotnet coverage
      run: |
        unzip "dotnet-code-coverage-${{hashFiles('dotnet/BirdApi/BeakPeekApi/packages.lock.json', 'dotnet/BirdApi/BeakPeekApi.Tests/packages.lock.json')}}" "dotnet-coverage"

    - name: unzip flutter
      run: |
        unzip "flutter-code-coverage-${{hashFiles('beakpeek/pubspec.lock')}}" "flutter-coverage"

    - name: list files
      run: ls

    - name: Upload coverage
      # if: ${{ !env.ACT }}
      uses: codecov/codecov-action@v4
      with:
        files: ./beakpeek/coverage/lcov.info, ./coverage.cobertura.xml
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
        verbose: true
        name: BeakPeek Coverage
