name: 🔀 Label Pull Requests

on:
  schedule:
    - cron: "0 1 * * *"

  pull_request:

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
